"""Starter medicine reference dataset for the medical RAG knowledge base.

Curated, conservative patient-education info for ~40 common medicines. This seeds
the engine so it works immediately; full DrugBank / OpenFDA / RxNorm ingestion is
a later ETL phase. Each entry: name, generic, purpose, how_it_works, side_effects,
warnings, food_instructions, timing.
"""
from __future__ import annotations

# fmt: off
MEDICINES: list[dict] = [
    {"name": "Paracetamol", "generic_name": "Acetaminophen", "purpose": "Fever and mild-to-moderate pain relief.",
     "how_it_works": "Acts on the brain's heat-regulating centre to reduce fever and raises the pain threshold.",
     "side_effects": "Generally well tolerated; rarely nausea or skin rash. Overdose can harm the liver.",
     "warnings": "Do not exceed 4 g per day. Avoid with heavy alcohol use or liver disease.",
     "food_instructions": "Can be taken with or without food.", "timing": "Every 4-6 hours as needed."},
    {"name": "Dolo 650", "generic_name": "Paracetamol 650mg", "purpose": "Fever and pain relief (higher-strength paracetamol).",
     "how_it_works": "Same as paracetamol — reduces fever and relieves pain.",
     "side_effects": "Usually minimal; rarely nausea. Excess dosing risks liver injury.",
     "warnings": "Max 3-4 tablets/day. Avoid alcohol.", "food_instructions": "With or without food.",
     "timing": "Every 6-8 hours as needed."},
    {"name": "Ibuprofen", "generic_name": "Ibuprofen", "purpose": "Pain, inflammation and fever relief (NSAID).",
     "how_it_works": "Blocks COX enzymes that produce prostaglandins, reducing pain and swelling.",
     "side_effects": "Stomach upset, heartburn; long-term use may affect stomach or kidneys.",
     "warnings": "Avoid with ulcers, kidney disease, or in late pregnancy. Take the lowest effective dose.",
     "food_instructions": "Take with food to protect the stomach.", "timing": "Every 6-8 hours with meals."},
    {"name": "Aspirin", "generic_name": "Acetylsalicylic acid", "purpose": "Pain/fever relief; low-dose for heart protection.",
     "how_it_works": "Inhibits prostaglandins and makes platelets less sticky, reducing clot risk.",
     "side_effects": "Stomach irritation, easy bruising or bleeding.",
     "warnings": "Not for children with viral illness (Reye's syndrome). Tell your doctor before surgery.",
     "food_instructions": "Take with food.", "timing": "Once daily (low-dose) or as directed."},
    {"name": "Diclofenac", "generic_name": "Diclofenac", "purpose": "Pain and inflammation relief (NSAID).",
     "how_it_works": "Reduces prostaglandins to relieve pain and swelling, e.g. arthritis or injury.",
     "side_effects": "Stomach upset, heartburn; may raise blood pressure.",
     "warnings": "Use cautiously with heart, kidney or stomach problems.",
     "food_instructions": "Take with food.", "timing": "Twice daily with meals."},
    {"name": "Amoxicillin", "generic_name": "Amoxicillin", "purpose": "Bacterial infections (throat, ear, chest, urine).",
     "how_it_works": "A penicillin antibiotic that stops bacteria from building their cell walls.",
     "side_effects": "Diarrhoea, nausea, rash.",
     "warnings": "Tell your doctor about any penicillin allergy. Complete the full course.",
     "food_instructions": "With or without food.", "timing": "Usually every 8 hours."},
    {"name": "Augmentin", "generic_name": "Amoxicillin + Clavulanic acid", "purpose": "Bacterial infections resistant to amoxicillin alone.",
     "how_it_works": "Amoxicillin kills bacteria; clavulanic acid blocks the enzyme bacteria use to resist it.",
     "side_effects": "Diarrhoea, nausea, stomach upset.",
     "warnings": "Avoid with penicillin allergy. Finish the full course.",
     "food_instructions": "Take at the start of a meal to reduce stomach upset.", "timing": "Every 12 hours."},
    {"name": "Azithromycin", "generic_name": "Azithromycin", "purpose": "Respiratory, skin and some sexually-transmitted infections.",
     "how_it_works": "A macrolide antibiotic that stops bacteria from making proteins.",
     "side_effects": "Nausea, diarrhoea, abdominal pain.",
     "warnings": "Tell your doctor about heart-rhythm problems. Complete the course.",
     "food_instructions": "With or without food.", "timing": "Once daily, often a 3-5 day course."},
    {"name": "Ciprofloxacin", "generic_name": "Ciprofloxacin", "purpose": "Urinary, gut and other bacterial infections.",
     "how_it_works": "A fluoroquinolone antibiotic that blocks bacterial DNA replication.",
     "side_effects": "Nausea, diarrhoea, dizziness; rarely tendon pain.",
     "warnings": "Avoid dairy/antacids around the dose. Report tendon or nerve pain.",
     "food_instructions": "Avoid milk and calcium near the dose.", "timing": "Every 12 hours."},
    {"name": "Doxycycline", "generic_name": "Doxycycline", "purpose": "Skin, chest, tick-borne and other infections.",
     "how_it_works": "A tetracycline antibiotic that stops bacterial protein synthesis.",
     "side_effects": "Nausea, sun sensitivity, throat irritation.",
     "warnings": "Avoid in pregnancy and young children. Use sun protection.",
     "food_instructions": "Take with a full glass of water; stay upright 30 min.", "timing": "Once or twice daily."},
    {"name": "Metformin", "generic_name": "Metformin", "purpose": "Type 2 diabetes — lowers blood sugar.",
     "how_it_works": "Reduces sugar made by the liver and improves the body's response to insulin.",
     "side_effects": "Nausea, diarrhoea, metallic taste (often settle with time).",
     "warnings": "Tell your doctor about kidney problems. Hold before contrast scans.",
     "food_instructions": "Take with meals to reduce stomach upset.", "timing": "With breakfast and/or dinner."},
    {"name": "Amlodipine", "generic_name": "Amlodipine", "purpose": "High blood pressure and chest pain (angina).",
     "how_it_works": "A calcium-channel blocker that relaxes and widens blood vessels.",
     "side_effects": "Ankle swelling, flushing, headache.",
     "warnings": "Don't stop suddenly. Report severe swelling or palpitations.",
     "food_instructions": "With or without food.", "timing": "Once daily, same time each day."},
    {"name": "Losartan", "generic_name": "Losartan", "purpose": "High blood pressure; protects kidneys in diabetes.",
     "how_it_works": "Blocks angiotensin II, relaxing blood vessels and lowering pressure.",
     "side_effects": "Dizziness, raised potassium.",
     "warnings": "Avoid in pregnancy. Monitor kidney function and potassium.",
     "food_instructions": "With or without food.", "timing": "Once daily."},
    {"name": "Telmisartan", "generic_name": "Telmisartan", "purpose": "High blood pressure.",
     "how_it_works": "An ARB that relaxes blood vessels by blocking angiotensin II.",
     "side_effects": "Dizziness, back pain.",
     "warnings": "Avoid in pregnancy. Monitor kidney function.",
     "food_instructions": "With or without food.", "timing": "Once daily."},
    {"name": "Metoprolol", "generic_name": "Metoprolol", "purpose": "High blood pressure, chest pain, irregular heartbeat.",
     "how_it_works": "A beta-blocker that slows the heart and reduces its workload.",
     "side_effects": "Tiredness, cold hands, slow pulse.",
     "warnings": "Do not stop abruptly. Caution with asthma.",
     "food_instructions": "Take with or just after food.", "timing": "Once or twice daily."},
    {"name": "Atorvastatin", "generic_name": "Atorvastatin", "purpose": "Lowers cholesterol; reduces heart-attack/stroke risk.",
     "how_it_works": "Blocks an enzyme the liver uses to make cholesterol.",
     "side_effects": "Muscle aches, mild digestive upset.",
     "warnings": "Report unexplained muscle pain. Avoid large amounts of grapefruit.",
     "food_instructions": "With or without food.", "timing": "Once daily, usually at night."},
    {"name": "Rosuvastatin", "generic_name": "Rosuvastatin", "purpose": "Lowers cholesterol.",
     "how_it_works": "A statin that reduces cholesterol production in the liver.",
     "side_effects": "Muscle aches, headache.",
     "warnings": "Report muscle pain or dark urine.",
     "food_instructions": "With or without food.", "timing": "Once daily."},
    {"name": "Omeprazole", "generic_name": "Omeprazole", "purpose": "Acidity, reflux (GERD) and ulcers.",
     "how_it_works": "A proton-pump inhibitor that reduces stomach-acid production.",
     "side_effects": "Headache, diarrhoea; long-term use may affect magnesium/B12.",
     "warnings": "Use the shortest effective course.",
     "food_instructions": "Take 30-60 min before a meal.", "timing": "Once daily before breakfast."},
    {"name": "Pantoprazole", "generic_name": "Pantoprazole", "purpose": "Acidity, reflux and ulcers.",
     "how_it_works": "A proton-pump inhibitor that lowers stomach acid.",
     "side_effects": "Headache, diarrhoea.",
     "warnings": "Use for the shortest needed duration.",
     "food_instructions": "Take before breakfast.", "timing": "Once daily before food."},
    {"name": "Ranitidine", "generic_name": "Ranitidine", "purpose": "Acidity and heartburn.",
     "how_it_works": "An H2 blocker that reduces stomach acid.",
     "side_effects": "Headache, constipation.",
     "warnings": "Follow your pharmacist's guidance on current availability.",
     "food_instructions": "With or without food.", "timing": "Once or twice daily."},
    {"name": "Domperidone", "generic_name": "Domperidone", "purpose": "Nausea, vomiting and bloating.",
     "how_it_works": "Speeds stomach emptying and blocks nausea signals.",
     "side_effects": "Dry mouth, headache.",
     "warnings": "Tell your doctor about heart-rhythm issues.",
     "food_instructions": "Take 15-30 min before meals.", "timing": "Before meals."},
    {"name": "Ondansetron", "generic_name": "Ondansetron", "purpose": "Strong nausea and vomiting (e.g. after surgery).",
     "how_it_works": "Blocks serotonin signals that trigger vomiting.",
     "side_effects": "Constipation, headache.",
     "warnings": "Report fast or irregular heartbeat.",
     "food_instructions": "With or without food.", "timing": "Every 8 hours as needed."},
    {"name": "Cetirizine", "generic_name": "Cetirizine", "purpose": "Allergies — sneezing, itching, hives.",
     "how_it_works": "An antihistamine that blocks histamine released during allergies.",
     "side_effects": "Mild drowsiness, dry mouth.",
     "warnings": "May cause drowsiness — be careful driving.",
     "food_instructions": "With or without food.", "timing": "Once daily, often at night."},
    {"name": "Levocetirizine", "generic_name": "Levocetirizine", "purpose": "Allergic rhinitis and hives.",
     "how_it_works": "An antihistamine that blocks histamine.",
     "side_effects": "Mild drowsiness, dry mouth.",
     "warnings": "Use caution when driving.",
     "food_instructions": "With or without food.", "timing": "Once daily at night."},
    {"name": "Montelukast", "generic_name": "Montelukast", "purpose": "Asthma and allergic rhinitis prevention.",
     "how_it_works": "Blocks leukotrienes that cause airway tightening and inflammation.",
     "side_effects": "Headache; rarely mood changes.",
     "warnings": "Report any mood or behaviour changes. Not for sudden asthma attacks.",
     "food_instructions": "With or without food.", "timing": "Once daily in the evening."},
    {"name": "Salbutamol", "generic_name": "Albuterol", "purpose": "Quick relief of asthma/breathlessness (inhaler).",
     "how_it_works": "Relaxes airway muscles to open the airways rapidly.",
     "side_effects": "Tremor, fast heartbeat.",
     "warnings": "If you need it very often, see your doctor — your control may need review.",
     "food_instructions": "Inhaled — not related to food.", "timing": "As needed for breathlessness."},
    {"name": "Prednisolone", "generic_name": "Prednisolone", "purpose": "Inflammation, allergies, autoimmune flare-ups (steroid).",
     "how_it_works": "A corticosteroid that calms the immune system and inflammation.",
     "side_effects": "Increased appetite, mood changes, raised sugar with longer use.",
     "warnings": "Do not stop suddenly after long courses — taper as advised.",
     "food_instructions": "Take with food.", "timing": "Once daily in the morning."},
    {"name": "Levothyroxine", "generic_name": "Levothyroxine", "purpose": "Underactive thyroid (hypothyroidism).",
     "how_it_works": "Replaces the thyroid hormone your body isn't making enough of.",
     "side_effects": "If dose is too high: palpitations, weight loss, anxiety.",
     "warnings": "Take consistently; routine blood tests guide the dose.",
     "food_instructions": "Empty stomach, 30-60 min before breakfast.", "timing": "Once daily in the morning."},
    {"name": "Insulin", "generic_name": "Insulin", "purpose": "Lowers blood sugar in diabetes.",
     "how_it_works": "Replaces or supplements the body's insulin to move sugar into cells.",
     "side_effects": "Low blood sugar (shakiness, sweating) if too much; injection-site reactions.",
     "warnings": "Learn to recognise and treat low sugar. Rotate injection sites.",
     "food_instructions": "Timed around meals as prescribed.", "timing": "As directed (before meals / bedtime)."},
    {"name": "Gliclazide", "generic_name": "Gliclazide", "purpose": "Type 2 diabetes — lowers blood sugar.",
     "how_it_works": "Stimulates the pancreas to release more insulin.",
     "side_effects": "Low blood sugar, weight gain.",
     "warnings": "Don't skip meals after taking it.",
     "food_instructions": "With breakfast.", "timing": "Once daily with the first meal."},
    {"name": "Hydrochlorothiazide", "generic_name": "Hydrochlorothiazide", "purpose": "High blood pressure and fluid retention (water pill).",
     "how_it_works": "Helps kidneys remove extra salt and water.",
     "side_effects": "Increased urination, low potassium, dizziness.",
     "warnings": "Monitor electrolytes. Take earlier in the day to avoid night-time urination.",
     "food_instructions": "With or without food.", "timing": "Once daily in the morning."},
    {"name": "Furosemide", "generic_name": "Furosemide", "purpose": "Fluid overload (heart failure, swelling).",
     "how_it_works": "A strong diuretic that makes kidneys remove excess fluid.",
     "side_effects": "Frequent urination, low potassium, dizziness.",
     "warnings": "Monitor electrolytes and kidney function.",
     "food_instructions": "With or without food.", "timing": "Morning (and midday if twice daily)."},
    {"name": "Clopidogrel", "generic_name": "Clopidogrel", "purpose": "Prevents blood clots after heart/stroke events.",
     "how_it_works": "Makes platelets less sticky to prevent clots.",
     "side_effects": "Easy bruising, bleeding.",
     "warnings": "Tell any doctor/dentist before procedures. Don't stop without advice.",
     "food_instructions": "With or without food.", "timing": "Once daily."},
    {"name": "Gabapentin", "generic_name": "Gabapentin", "purpose": "Nerve pain and certain seizures.",
     "how_it_works": "Calms overactive nerve signals.",
     "side_effects": "Drowsiness, dizziness, swelling.",
     "warnings": "Don't stop suddenly. Avoid alcohol; be careful driving.",
     "food_instructions": "With or without food.", "timing": "Usually two-three times daily."},
    {"name": "Sertraline", "generic_name": "Sertraline", "purpose": "Depression and anxiety disorders.",
     "how_it_works": "An SSRI that increases serotonin activity in the brain.",
     "side_effects": "Nausea, sleep changes, reduced libido (often ease over weeks).",
     "warnings": "May take 2-4 weeks to work. Don't stop abruptly. Report mood worsening.",
     "food_instructions": "With food to reduce nausea.", "timing": "Once daily, consistent time."},
    {"name": "Amitriptyline", "generic_name": "Amitriptyline", "purpose": "Nerve pain, migraine prevention, low mood.",
     "how_it_works": "Adjusts brain chemicals involved in pain and mood.",
     "side_effects": "Drowsiness, dry mouth, constipation.",
     "warnings": "Be careful driving. Don't stop suddenly.",
     "food_instructions": "With or without food.", "timing": "At night."},
    {"name": "Vitamin D3", "generic_name": "Cholecalciferol", "purpose": "Vitamin D deficiency; bone health.",
     "how_it_works": "Replenishes vitamin D to help absorb calcium for bones.",
     "side_effects": "Rare unless overdosed (high calcium).",
     "warnings": "Follow the prescribed dose; very high doses can be harmful.",
     "food_instructions": "Take with a meal containing some fat.", "timing": "Daily or weekly as prescribed."},
    {"name": "Calcium + Vitamin D", "generic_name": "Calcium carbonate + Vitamin D3", "purpose": "Bone health and calcium supplementation.",
     "how_it_works": "Provides calcium with vitamin D to aid absorption.",
     "side_effects": "Constipation, bloating.",
     "warnings": "Separate from certain antibiotics/thyroid medicines by a few hours.",
     "food_instructions": "Take with food.", "timing": "Once or twice daily."},
    {"name": "Folic Acid", "generic_name": "Folic acid", "purpose": "Prevents/treats folate deficiency; pregnancy support.",
     "how_it_works": "A B-vitamin needed to make healthy red blood cells and DNA.",
     "side_effects": "Very rare.",
     "warnings": "Important in early pregnancy as advised.",
     "food_instructions": "With or without food.", "timing": "Once daily."},
    {"name": "Iron (Ferrous sulfate)", "generic_name": "Ferrous sulfate", "purpose": "Iron-deficiency anaemia.",
     "how_it_works": "Replenishes iron to make haemoglobin in red blood cells.",
     "side_effects": "Constipation, dark stools, stomach upset.",
     "warnings": "Keep away from children. Separate from tea/coffee and calcium.",
     "food_instructions": "Best on an empty stomach, or with food if it upsets you. Vitamin C aids absorption.",
     "timing": "Once daily."},
]
# fmt: on
