export const metadata = { title: "Terms of Service — OmniAssist Health" };

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> June 2026</p>

      <p>
        These Terms govern your use of OmniAssist Health. By creating an account you agree to them.
      </p>

      <h2>1. The service</h2>
      <p>
        OmniAssist Health reads and explains prescriptions and lab reports, answers general health
        questions, and helps clinics manage patients, doctors and appointments. Features depend on
        your subscription plan.
      </p>

      <h2>2. Not medical advice</h2>
      <p>
        OmniAssist Health provides AI-generated information for understanding only. It does not
        diagnose, prescribe, or replace a qualified healthcare professional. Always consult a doctor
        for personal medical decisions, and seek emergency care for urgent symptoms.
      </p>

      <h2>3. Accounts</h2>
      <p>
        You are responsible for your account, your clinic staff, and the content you upload. You
        must have the right to use any health data you add, and to comply with applicable
        patient-privacy laws.
      </p>

      <h2>4. Acceptable use</h2>
      <p>
        Don&apos;t use the service to send spam, violate laws, infringe rights, or attempt to
        disrupt or reverse-engineer the platform. We may suspend accounts that abuse the service.
      </p>

      <h2>5. Plans, billing &amp; trials</h2>
      <p>
        Paid plans are billed monthly or annually. A 14-day free trial is available; you can cancel
        anytime before renewal. Fees are non-refundable except as described in our refund policy.
      </p>

      <h2>6. AI output</h2>
      <p>
        AI responses are generated by language models and may be imperfect or incomplete. They are
        for general understanding only — always review AI output and confirm anything health-related
        with a qualified professional before relying on it.
      </p>

      <h2>7. Liability</h2>
      <p>
        The service is provided &quot;as is.&quot; To the maximum extent permitted by law, our
        liability is limited to the fees you paid in the prior 12 months.
      </p>

      <h2>8. Contact</h2>
      <p>
        Questions about these Terms? Email <strong>legal@omniassist.ai</strong>.
      </p>

      <p className="mt-8 text-xs">
        This document is a template for demonstration. Have it reviewed by legal counsel before
        production use.
      </p>
    </>
  );
}
